# Databricks notebook source
# MAGIC %md
# MAGIC # Gold Layer — Demand Report
# MAGIC
# MAGIC **Purpose:** Build the authoritative demand report used for forecasting and KPI reporting.
# MAGIC Port of the production dbt model `trf_br_demand_rpt`.
# MAGIC
# MAGIC **Pipeline stage:** Gold (business-ready)
# MAGIC
# MAGIC **Table created:**
# MAGIC - `gold.demand_rpt` — Enriched sales order lines with UOM conversion, pricing,
# MAGIC   org structure, and the composite business key (`KEY`).
# MAGIC
# MAGIC **Business key (`KEY`):**
# MAGIC `concat(segment_profit_center, plant, material_number)`
# MAGIC Used as the grain identifier for downstream time-series forecasting.
# MAGIC
# MAGIC **Surrogate key (`sk_demand`):**
# MAGIC `md5(order_number || '|' || order_item || '|' || schedule_line)`
# MAGIC Unique row identifier with no business meaning.

# COMMAND ----------

# MAGIC %md ## Configuration
# MAGIC
# MAGIC `PLANT_CODES` and `ORDER_TYPES` are set to match the anonymized sample data.
# MAGIC In production these would be parameterized via Databricks Widgets.

# COMMAND ----------

from pyspark.sql import functions as F
from pyspark.sql.types import DecimalType, LongType
from datetime import datetime

SILVER_SCHEMA = "silver"
GOLD_SCHEMA   = "gold"
CATALOG       = "main"

spark.sql(f"CREATE SCHEMA IF NOT EXISTS {CATALOG}.{GOLD_SCHEMA}")

# ---------------------------------------------------------------------------
# Pipeline filter constants — generated by scripts/anonymize.py
# In production: use Databricks Widgets or a config table
# ---------------------------------------------------------------------------
dbutils.widgets.text("plant_codes", "PLNT-01,PLNT-02,PLNT-03,PLNT-04,PLNT-05,PLNT-06")
dbutils.widgets.text("order_types", "ORD-TYPE-A,ORD-TYPE-B,ORD-TYPE-C")

PLANT_CODES  = [p.strip() for p in dbutils.widgets.get("plant_codes").split(",")]
ORDER_TYPES  = [t.strip() for t in dbutils.widgets.get("order_types").split(",")]

print(f"Plant codes filter : {PLANT_CODES}")
print(f"Order types filter : {ORDER_TYPES}")
RUN_TS = datetime.utcnow().isoformat()

# COMMAND ----------

# MAGIC %md ## Load Silver tables

# COMMAND ----------

orders      = spark.table(f"{CATALOG}.{SILVER_SCHEMA}.orders")
materials   = spark.table(f"{CATALOG}.{SILVER_SCHEMA}.materials")
valuation   = spark.table(f"{CATALOG}.{SILVER_SCHEMA}.valuation")
uom_conv    = spark.table(f"{CATALOG}.{SILVER_SCHEMA}.uom_conversion")
profit_ctrs = spark.table(f"{CATALOG}.{SILVER_SCHEMA}.profit_centers")

# COMMAND ----------

# MAGIC %md ## Step 1 — Filter orders by plant and order type

# COMMAND ----------

orders_filtered = (
    orders
    .filter(F.col("plant").isin(PLANT_CODES))
    .filter(F.col("order_type").isin(ORDER_TYPES))
    .filter(F.col("delivery_date").isNotNull())
)
print(f"Orders after filter: {orders_filtered.count():,}")

# COMMAND ----------

# MAGIC %md ## Step 2 — Join UOM conversion factors
# MAGIC
# MAGIC Computes the factor to convert `sales_uom` → `base_uom` using MARM.
# MAGIC If sales_uom == base_uom, no conversion needed (factor = 1).

# COMMAND ----------

# Resolve each material's base UOM from silver.materials
mat_base_uom = (
    materials
    .select("material_number", "plant", "base_uom")
    .dropDuplicates(["material_number", "plant"])
)

# Join to get base_uom per order line
orders_with_uom = orders_filtered.join(
    mat_base_uom,
    on=["material_number", "plant"],
    how="left",
)

# UOM conversion factors: in_uom (sales) → base_uom
uom_in = (
    uom_conv
    .withColumnRenamed("material_number", "mat_uom")
    .withColumnRenamed("alt_uom", "in_uom")
    .withColumnRenamed("numerator", "in_numerator")
    .withColumnRenamed("denominator", "in_denominator")
    .select("mat_uom", "in_uom", "in_numerator", "in_denominator")
)

orders_uom = (
    orders_with_uom
    .join(
        uom_in,
        (F.col("material_number") == F.col("mat_uom")) & (F.col("sales_uom_vbap") == F.col("in_uom")),
        how="left",
    )
    .drop("mat_uom", "in_uom")
)

# Compute quantity in base UOM
# If sales UOM == base UOM: no conversion. Otherwise: qty * (in_num / in_den)
orders_qty = orders_uom.withColumn(
    "quantity_base_uom",
    F.when(
        F.col("sales_uom_vbap") == F.col("base_uom"),
        F.col("order_qty"),
    ).otherwise(
        (
            F.col("order_qty")
            * (F.col("in_numerator") / F.col("in_denominator"))
        ).cast(DecimalType(18, 3))
    ),
).withColumn(
    "quantity_base_uom",
    F.coalesce(F.col("quantity_base_uom"), F.col("order_qty")),  # fallback: use order_qty
).withColumn(
    "quantity_base_uom",
    F.col("quantity_base_uom").cast(LongType()),  # integer quantity per original model
)

# COMMAND ----------

# MAGIC %md ## Step 3 — Enrich with material master and profit center

# COMMAND ----------

mat_attrs = (
    materials
    .select(
        "material_number", "plant",
        "mrp_controller", "profit_center", "purchasing_group",
        "base_uom", "material_description",
    )
    .dropDuplicates(["material_number", "plant"])
)

valuation_attrs = (
    valuation
    .select(
        F.col("material_number").alias("v_matnr"),
        F.col("plant").alias("v_plant"),
        F.col("moving_avg_price").alias("unit_price"),
        F.col("valuation_class"),
    )
    .dropDuplicates(["v_matnr", "v_plant"])
)

enriched = (
    orders_qty
    .join(mat_attrs, on=["material_number", "plant"], how="left")
    .join(
        valuation_attrs,
        (F.col("material_number") == F.col("v_matnr")) & (F.col("plant") == F.col("v_plant")),
        how="left",
    )
    .drop("v_matnr", "v_plant")
    .join(profit_ctrs, on="profit_center", how="left")
)

# COMMAND ----------

# MAGIC %md ## Step 4 — Compute KEY and surrogate key

# COMMAND ----------

demand_rpt = (
    enriched
    .withColumn(
        "KEY",
        F.concat(
            F.coalesce(F.col("segment_profit_center"), F.lit("")),
            F.col("plant"),
            F.col("material_number"),
        ),
    )
    .withColumn(
        "sk_demand",
        F.md5(
            F.concat_ws("|",
                F.col("order_number"),
                F.col("order_item"),
                F.col("schedule_line"),
            )
        ),
    )
    .withColumn("_processed_at", F.lit(RUN_TS))
    .filter(F.col("segment_profit_center").isNotNull())
    .filter(F.col("department").isNotNull())
    .select(
        "sk_demand",
        "order_number",
        "order_item",
        "schedule_line",
        "delivery_date",
        "material_number",
        "plant",
        "item_category",
        "mrp_controller",
        "profit_center",
        "segment_profit_center",
        "department",
        "purchasing_group",
        "base_uom",
        F.col("sales_uom_vbap").alias("sales_uom"),
        "quantity_base_uom",
        "order_qty",
        "material_description",
        "unit_price",
        "valuation_class",
        "order_type",
        "sales_org",
        "distribution_channel",
        "customer_number",
        "KEY",
        "_processed_at",
    )
)

# COMMAND ----------

# MAGIC %md ## Step 5 — Data Quality checks on Gold output

# COMMAND ----------

total = demand_rpt.count()
print(f"\nGold demand_rpt rows: {total:,}")

checks = [
    ("not_null:sk_demand",            F.col("sk_demand").isNotNull()),
    ("unique:sk_demand",              None),  # handled separately
    ("not_null:KEY",                  F.col("KEY").isNotNull() & (F.col("KEY") != "")),
    ("not_null:material_number",      F.col("material_number").isNotNull() & (F.col("material_number") != "")),
    ("not_null:plant",                F.col("plant").isNotNull() & (F.col("plant") != "")),
    ("not_null:segment_profit_center",F.col("segment_profit_center").isNotNull()),
    ("positive:quantity_base_uom",    F.col("quantity_base_uom") > 0),
    ("valid_delivery_date",           F.col("delivery_date") >= F.lit("2015-01-01").cast("date")),
]

for check_name, expr in checks:
    if check_name == "unique:sk_demand":
        dup = total - demand_rpt.dropDuplicates(["sk_demand"]).count()
        status = "PASS" if dup == 0 else "WARN"
        print(f"  [{status}] {'✓' if status=='PASS' else '⚠'} gold.demand_rpt.{check_name} — {dup} duplicates")
    else:
        fail = demand_rpt.filter(~expr).count()
        status = "PASS" if fail == 0 else "WARN"
        print(f"  [{status}] {'✓' if status=='PASS' else '⚠'} gold.demand_rpt.{check_name} — {fail} failures")

# COMMAND ----------

# MAGIC %md ## Step 6 — Write Gold table

# COMMAND ----------

(
    demand_rpt.write
    .format("delta")
    .mode("overwrite")
    .option("overwriteSchema", "true")
    .saveAsTable(f"{CATALOG}.{GOLD_SCHEMA}.demand_rpt")
)

print(f"\n✓ gold.demand_rpt written: {demand_rpt.count():,} rows")
print(f"  Unique KEYs : {demand_rpt.select('KEY').distinct().count():,}")
print(f"  Date range  : {demand_rpt.agg(F.min('delivery_date'), F.max('delivery_date')).first()}")
print(f"\n=== Gold layer complete ===")
