# Auto-generated by scripts/anonymize.py
# Use these constants in the Gold notebook filters

PLANT_CODES = ['PLNT-01', 'PLNT-02', 'PLNT-03', 'PLNT-04', 'PLNT-05', 'PLNT-06', 'PLNT-07', 'PLNT-08', 'PLNT-09', 'PLNT-10', 'PLNT-11', 'PLNT-12', 'PLNT-13', 'PLNT-14', 'PLNT-15', 'PLNT-16', 'PLNT-17', 'PLNT-18', 'PLNT-19', 'PLNT-20', 'PLNT-21', 'PLNT-22', 'PLNT-23', 'PLNT-24', 'PLNT-25', 'PLNT-26', 'PLNT-27', 'PLNT-28', 'PLNT-29', 'PLNT-30', 'PLNT-31', 'PLNT-32', 'PLNT-33', 'PLNT-34', 'PLNT-35', 'PLNT-36', 'PLNT-37', 'PLNT-38', 'PLNT-39', 'PLNT-40', 'PLNT-41', 'PLNT-42', 'PLNT-43', 'PLNT-44', 'PLNT-45', 'PLNT-46', 'PLNT-47', 'PLNT-48', 'PLNT-49', 'PLNT-50']
ORDER_TYPES = ['ORD-TYPE-A', 'ORD-TYPE-B', 'ORD-TYPE-C']

# Mapping reference (original → anonymized) — DO NOT COMMIT to git
# MATNR: 4660 materials mapped
# WERKS: 50 plants mapped
# PRCTR: 731 profit centers mapped
# NPRCTR: 28 segments mapped